AllCops:
  Exclude:
    - 'vendor/**/*'

Style/SingleSpaceBeforeFirstArg:
  Exclude:
    - '**/Berksfile'
    - '**/metadata.rb'

Style/FileName:
  Exclude:
    - '**/Gemfile'
    - '**/Berksfile'

Style/RegexpLiteral:
  Exclude:
    - '**/Guardfile'

Style/EmptyLines:
  Exclude:
    - '**/Guardfile'
    - '**/Rakefile'

Style/TrailingBlankLines:
  Exclude:
    - '**/Guardfile'
    - '**/Rakefile'

Metrics/LineLength:
  Max: 100
  Exclude:
    - '**/Gemfile'
    - '**/attributes/default.rb'
    - '**/test/integration/default/serverspec/recipes/default_spec.rb'
    - '**/libraries/default.rb'

Metrics/MethodLength:
  Max: 20
